# This example configuration file is only for testing of bootstrap scripts.
# Normally, this configuration is generated by bootstrap Salt state.

target_platform = 'rhel7'

init_ip_route = {

    # IP address to route IP traffic by default.
    'default_route_ip': '192.168.50.1',

    # IP address behind network router to confirm successful routing configuration.
    'remote_network_ip': '8.8.8.8',

}

init_dns_server = {

    'resolv_conf_file': 'resources/examples/uvsmtid/centos-7.0-minimal/resolv.conf',

    'dns_server_ip': '8.8.8.8',

    'remote_hostname': 'google.com',

}

make_salt_resolvable = {

    'required_entries_hosts_file': 'resources/examples/uvsmtid/centos-7.0-minimal/hosts_file',

}

init_yum_repos = {

    "yum_repo_configs": {

        "base": {
            "installation_type": "file",
            # TODO
        },

        "epel": {
            "installation_type": "rpm",
            "rpm_key_file": "resources/examples/uvsmtid/centos-7.0-minimal/RPM-GPG-KEY-EPEL-7.352C64E5.txt",
            # TODO
        },

        "pgdg": {
            "installation_type": "rpm",
            # TODO
        },
    },

}

install_salt_master = {

    "salt_master_config_file": "resources/examples/uvsmtid/centos-7.0-minimal/master.conf",

    "rpm_sources": {
        "salt-master": {
            "source_type": "tar",
            "file_path": "resources/examples/uvsmtid/centos-7.0-minimal/salt-master-2014.7.1-1.el7.x86_64.rpms.tar",
        },
    },

}

install_salt_minion = {

    "salt_minion_config_file": "resources/examples/uvsmtid/centos-7.0-minimal/minion.conf",

    "rpm_sources": {
        "salt-master": {
            "source_type": "tar",
            "file_path": "resources/examples/uvsmtid/centos-7.0-minimal/salt-minion-2014.7.1-1.el7.x86_64.rpms.tar",
        },
    },

}

activate_salt_master = {

    'service_name': 'salt-master',

}

activate_salt_minion = {

    'service_name': 'salt-minion',

}


