# This example configuration file is only for testing of bootstrap scripts.
# Normally, this configuration is generated by bootstrap Salt state.

target_platform = 'generic_linux'

init_ip_route = {

    # IP address to route IP traffic by default.
    'default_route_ip': '192.168.50.1',

    # IP address behind network router to confirm successful routing configuration.
    'remote_network_ip': '8.8.8.8',

}

init_dns_server = {

    'dns_server_ip': '8.8.8.8',

    'remote_hostname': 'google.com',

}


